name: google-java-format # 워크플로우의 이름

on: [ push, pull_request ] # 깃 저장소의 push, pull_request 이벤트에 의해 트리거된다.
jobs:

  formatting:
    runs-on: ubuntu-latest # 워크플로우의 이름
    steps:
      - uses: actions/checkout@v2 # 깃허브 저장소를 체크아웃 하는 액션

      - uses: axel-op/googlejavaformat-action@v3 # 본격적인 google-java-format 실행
        with:
          args: "--replace --aosp" # --replace (파일을 수정한다) --aosp(인덴트 4로 설정, AOSP 스타일)
          commitMessage: "Format : Google Java Format" # 커밋 메시지 이름 설정
