# Example workflow
name: Format

on: [ push, pull_request ]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--aosp --replace"
          # --aosp : "안드로이드 오픈소스 프로젝트 스타일"의 약자로 default 세팅인 indentation 2 를 4로 적용
          # --replace : 포매팅을 출력하지 않고 파일들에 적용
          commitMessage: "Format : Google Java Format"
          # 디폴트 커밋 메시지인 "Google Java Format" 을 커밋 메시지 컨벤션에 맞게 적용

