name: Build
on:
  push:
    branches:
      - master # or the name of your main branch
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: self-hosted
    steps:
      - uses: philips-software/sonar-scanner-action@<version>
        with:
          token: ${{ secrets.SONAR_TOKEN }}
          projectKey: project.key.from.sonar.qube
          baseDir: .
          url: ${{ secrets.SONAR_HOST_URL }}
          enablePullRequestDecoration: true
          isCommunityEdition: true

