name: Build
on:
  push:
    branches:
      - master # or the name of your main branch
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - run: echo pwd
      - run: echo "--------------------"
      - run: echo "--------------------"
      - run: echo "--------------------"
      - run: echo "--------------------"
      - run: echo "--------------------"
      - uses: philips-software/sonar-scanner-action@v1.3.0
        with:
          token: ${{ secrets.SONAR_TOKEN }}
          projectKey: project.key.from.sonar.qube
          projectName: inbobwetrust
          baseDir: /github/workspace
          url: ${{ secrets.SONAR_HOST_URL }}
          enablePullRequestDecoration: true
          isCommunityEdition: true

