name: Build
on:
  push:
    branches:
      - master # or the name of your main branch
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_PROJECT_KEY: f4af627e19ec8a980d527d3971d6e5bec20fd373

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectKey: 'f4af627e19ec8a980d527d3971d6e5bec20fd373'
      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time
        timeout-minutes: 5
        with:
          projectKey: 'f4af627e19ec8a980d527d3971d6e5bec20fd373'

